version: '3'
name: web-text-analysis

services:
  jupyter:
    image: jupyter/base-notebook
    user: root
    environment:
      - GRANT_SUDO=yes
    env_file:
      - .env
    build: .
    volumes:
      - .:/home/jovyan
      - 'conda-packages:/opt/conda/lib/python3.10/site-packages/'
    ports:
      - "8888:8888"

volumes:
  conda-packages:
    name: 'conda-python310-libs'
