version: '3'
name: web-text-analysis

services:
  jupyter:
    image: jupyter/base-notebook
    user: root
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=my-secret-token
    build: .
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - "8888:8888"
