version: '3'
name: web-text-analysis

services:
  jupyter:
    image: jupyter/base-notebook
    user: root
    environment:
      - GRANT_SUDO=yes
    env_file:
      - .env
    build: .
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./requirements.txt:/tmp/requirements.txt
    ports:
      - "8888:8888"
